
-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- VOTERS TABLE
create table if not exists public.voters (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone text,
  neighborhood text,
  status text check (status in ('ganho', 'indeciso', 'perdido', 'pendente')) default 'pendente',
  leader text,
  last_contact timestamp with time zone,
  notes text,
  user_id uuid references auth.users(id) -- Optional: link to auth user if needed
);

-- Enable RLS for voters
alter table public.voters enable row level security;

-- Policy: Allow all access for now (Development) - User should refine this
create policy "Allow all access to voters"
  on public.voters for all
  using (true)
  with check (true);


-- DEMANDS TABLE
create table if not exists public.demands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  local text,
  category text,
  status text check (status in ('pending', 'in-progress', 'resolved')) default 'pending',
  priority text check (priority in ('low', 'medium', 'high')) default 'medium',
  description text
);

-- Enable RLS for demands
alter table public.demands enable row level security;

create policy "Allow all access to demands"
  on public.demands for all
  using (true)
  with check (true);


-- DEMAND VISITS TABLE
create table if not exists public.demand_visits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  demand_id bigint references public.demands(id) on delete cascade,
  date date,
  responsible text,
  notes text,
  photo_url text
);

-- Enable RLS for demand_visits
alter table public.demand_visits enable row level security;

create policy "Allow all access to demand_visits"
  on public.demand_visits for all
  using (true)
  with check (true);

-- LEADS TABLE (Legacy/Extra support)
create table if not exists public.leads (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  full_name text,
  email text,
  phone text,
  specialty text
);

alter table public.leads enable row level security;

create policy "Allow all access to leads"
  on public.leads for all
  using (true)
  with check (true);
